# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53495a667c5680209aa890c5d4878e4cb4f7b8564912ceb1a863940467f32ce3254cb8b791d5b1b6b0e5ba752823a6034cd91bd91742c5ca3e092029d453523d

test:
  secret_key_base: acf94add7b546e3a4f6725534625083b5cfe48dec4b692c07c3876ab4a7ea259ef158dd5b9fe772faedf1de9c6bc519a9ce3e2e74a9cf584d69c6c2bba9b3350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
